title: Nathanael Ochoa
#logo:
description: descripton of website here
email: nathanael.ochoa.18@gmail.com
phone: (661) 210-5019
social_links:
 linkedin: https://www.linkedin.com/in/nathanael-ochoa/
show_downloads: false
theme: jekyll-theme-minimal
