title: Nathanael Ochoa
#logo:
description: 
Contact
nathanael.ochoa.18@gmail.com
(661) 210-5019
#minima:
 # social_links:
   # linkedin: https://www.linkedin.com/in/nathanael-ochoa/
show_downloads: false
theme: jekyll-theme-minimal
