title: Nathanael Ochoa
#logo:
description: > 
 descripton of website here.
 email - nathanael.ochoa.18@gmail.com
 phone - (661) 210-5019
minima:
 social_links:
  linkedin: name
show_downloads: false
theme: jekyll-theme-minimal
