title: Nathanael Ochoa
#logo:
description: > 
 descripton of website here.
 
 email - nathanael.ochoa.18@gmail.com
 
 phone - (661) 210-5019
linkedin_username: Nathanael
email: email@.com
theme: jekyll-theme-minimal
