title: Nathanael Ochoa
#logo:
description: |
 Email: nathanael.ochoa.18@gmail.com
 Phone No: (661) 210-5019
 LinkedIn: https://www.linkedin.com/in/nathanael-ochoa/
linkedin_username: Nathanael
email: email@.com
theme: jekyll-theme-minimal
